version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "crates/tosca"
      - "crates/tosca-*"
      - "crates/tosca-os/examples/light"
      - "crates/tosca-os/examples/ip-camera"
      - "crates/tosca-esp32c3/examples/light"
      - "crates/tosca-esp32c3/examples/light-with-state"
      - "crates/tosca-esp32c3/examples/light-with-events"
    schedule:
      interval: "daily"
